# Generated by Django 2.2 on 2019-12-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Картинка')),
                ('text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайк')),
                ('author_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пользователь')),
            ],
        ),
    ]
