# Generated by Django 2.2 on 2019-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Фотография')),
            ],
        ),
    ]
